(()=>{const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],num=v=>Number.isFinite(Number(v))?Number(v):0;
let tokens=[],filter='all',search='',events=[];
const avatar=t=>{const a=String(t.address||'');return a?'<img class="token-avatar-img" src="https://dd.dexscreener.com/ds-data/tokens/solana/'+a+'.png" alt="" loading="lazy" onerror="this.style.display=\'none\'">':'<span class="token-avatar blue">'+String(t.symbol||'?')[0]+'</span>'};
const compact=v=>{v=num(v);return v>=1e9?'$'+(v/1e9).toFixed(1)+'B':v>=1e6?'$'+(v/1e6).toFixed(1)+'M':v>=1e3?'$'+(v/1e3).toFixed(1)+'K':'$'+Math.round(v)};
const price=v=>{v=num(v);return v?('$'+(v>=1?v.toLocaleString(undefined,{maximumFractionDigits:4}):v>=.01?v.toFixed(4):v.toPrecision(4))):'—'};
const ago=t=>t?.pairCreatedAt?Math.max(0,(Date.now()-num(t.pairCreatedAt))/36e5):9999;
const ageText=h=>h<1?Math.max(1,Math.round(h*60))+'m':h<48?Math.round(h)+'h':Math.round(h/24)+'d';
const buys=t=>Math.round(num(t.buys)/(Math.max(1,num(t.buys)+num(t.sells)))*100);
function score(t){let a=ago(t),tx=num(t.buys5)+num(t.sells5),p=tx?num(t.buys5)/tx:.5,s=30+Math.min(25,Math.max(0,num(t.m5)*3))+Math.min(18,Math.max(0,num(t.h1)))+Math.min(15,(p-.5)*35)+Math.min(12,Math.log10(Math.max(1,tx))*4)+(a<24?10:0);return Math.max(0,Math.min(100,Math.round(s)))}
function risk(t){let x=25,l=num(t.liquidity),a=ago(t);if(l<25000)x+=40;else if(l<100000)x+=20;if(a<2)x+=12;if(num(t.buys1)+num(t.sells1)<10)x+=10;return Math.min(100,Math.round(x))}
function signal(t){return t.risk>=70?'RISK':t.combined>=80?'HOT':t.combined>=60?'WATCH':ago(t)<24?'NEW':'WATCH'}
function normalize(x){return{address:String(x.baseToken?.address||''),poolAddress:String(x.pairAddress||''),symbol:String(x.baseToken?.symbol||'UNKNOWN').toUpperCase(),name:String(x.baseToken?.name||x.baseToken?.symbol||'Unknown token'),price:num(x.priceUsd),m5:num(x.priceChange?.m5),h1:num(x.priceChange?.h1),h24:num(x.priceChange?.h24),volume:num(x.volume?.h24),liquidity:num(x.liquidity?.usd),buys:num(x.txns?.h24?.buys),sells:num(x.txns?.h24?.sells),buys5:num(x.txns?.m5?.buys),sells5:num(x.txns?.m5?.sells),buys1:num(x.txns?.h1?.buys),sells1:num(x.txns?.h1?.sells),pairCreatedAt:num(x.pairCreatedAt),url:String(x.url||'https://dexscreener.com/solana/'+x.pairAddress)}}
async function fetchJson(url){const c=new AbortController(),tm=setTimeout(()=>c.abort(),9000);try{const r=await fetch(url,{cache:'no-store',signal:c.signal});if(!r.ok)throw Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(tm)}}
async function getLive(){try{const p=await fetchJson('/api/market');if(Array.isArray(p.data)&&p.data.length>=5)return p.data.map(x=>({address:String(x.address||''),poolAddress:String(x.poolAddress||''),symbol:String(x.symbol||'UNKNOWN').toUpperCase(),name:String(x.name||x.symbol||'Unknown token'),price:num(x.price),m5:num(x.m5),h1:num(x.h1),h24:num(x.h24),volume:num(x.volume),liquidity:num(x.liquidity),buys:num(x.buys),sells:num(x.sells),buys5:num(x.buys5),sells5:num(x.sells5),buys1:num(x.buys1),sells1:num(x.sells1),pairCreatedAt:num(x.pairCreatedAt),url:String(x.url||'https://dexscreener.com/solana/'+x.poolAddress)}))}catch(e){} let all=[];for(const q of ['SOL','meme','pump','dog','cat','inu','ai']){try{const d=await fetchJson('https://api.dexscreener.com/latest/dex/search?q='+encodeURIComponent(q));all.push(...(d.pairs||[]).filter(x=>x.chainId==='solana'))}catch{}}
let seen=new Set();let out=all.filter(x=>{let a=x.baseToken?.address;if(!a||seen.has(a))return false;seen.add(a);return true}).map(normalize);
if(out.length<5){try{const d=await fetchJson('https://api.geckoterminal.com/api/v2/networks/solana/trending_pools?page=1');out=(d.data||[]).map(x=>{const a=x.attributes||{},id=String(x.id||'').replace(/^solana_/,'').split('_')[0],b=String(x.relationships?.base_token?.data?.id||'').replace(/^solana_/,'');return{address:b||id,poolAddress:id,symbol:String(a.name||'UNKNOWN').split(' / ')[0],name:String(a.name||'UNKNOWN').split(' / ')[0],price:num(a.base_token_price_usd),m5:num(a.price_change_percentage?.m5),h1:num(a.price_change_percentage?.h1),h24:num(a.price_change_percentage?.h24),volume:num(a.volume_usd?.h24),liquidity:num(a.reserve_in_usd),buys:num(a.transactions?.h24?.buys),sells:num(a.transactions?.h24?.sells),buys5:num(a.transactions?.m5?.buys),sells5:num(a.transactions?.m5?.sells),buys1:num(a.transactions?.h1?.buys),sells1:num(a.transactions?.h1?.sells),pairCreatedAt:a.pool_created_at?Date.parse(a.pool_created_at):0,url:'https://geckoterminal.com/solana/pools/'+id}})}catch{}}
if(!out.length)throw Error('No live Solana market data');return out}
function prepare(a){return a.filter(t=>t.address).map(t=>{t.combined=score(t);t.risk=risk(t);t.signal=signal(t);return t}).sort((a,b)=>b.combined-a.combined)}
function row(t,i){return '<tr><td>'+(i+1)+'</td><td><div class="token-cell"><span class="token-avatar blue">'+t.symbol[0]+'</span><span><b>'+t.symbol+'</b><small>'+t.name+'</small></span></div></td><td>'+price(t.price)+'</td><td class="'+(t.h1>=0?'gain':'loss')+'">'+(t.h1>=0?'+':'')+t.h1.toFixed(2)+'%</td><td class="'+(t.h24>=0?'gain':'loss')+'">'+(t.h24>=0?'+':'')+t.h24.toFixed(2)+'%</td><td>'+compact(t.volume)+'</td><td>'+compact(t.liquidity)+'</td><td><span class="signal '+t.signal.toLowerCase()+'">'+t.signal+' '+t.combined+'</span></td><td><a class="star" href="'+t.url+'" target="_blank">↗</a></td></tr>'}
function render(){
if($('#live-clock'))$('#live-clock').textContent=new Date().toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',second:'2-digit'});
let a=tokens;if(filter==='trending')a=a.filter(t=>t.combined>=60);if(filter==='gainers')a=a.filter(t=>t.h24>0);if(filter==='new')a=a.filter(t=>ago(t)<24);if(search)a=a.filter(t=>(t.symbol+' '+t.name+' '+t.address).toLowerCase().includes(search));if($('#token-list'))$('#token-list').innerHTML=a.map(row).join('')||'<tr><td colspan="9" class="empty">No matching live tokens.</td></tr>';
let hot=tokens[0];if(hot&&$('#radar-pick-content'))$('#radar-pick-content').innerHTML='<div class="opportunity-top"><div class="token-cell"><span class="token-avatar blue">'+hot.symbol[0]+'</span><span><h3 class="token-title">'+hot.symbol+'</h3><p class="muted">'+hot.name+'</p></span></div><div class="score">'+hot.combined+'<small>/100</small></div></div><div class="score-bar"><span style="width:'+hot.combined+'%"></span></div><p class="opportunity-copy">Live momentum: '+(hot.m5>=0?'+':'')+hot.m5.toFixed(2)+'% in 5m, '+buys(hot)+'% buy pressure, '+compact(hot.volume)+' volume and '+compact(hot.liquidity)+' liquidity.</p>';
if($('#new-radar-grid'))$('#new-radar-grid').innerHTML=tokens.slice().sort((a,b)=>ago(a)-ago(b)).slice(0,6).map(t=>'<article class="early-card"><div class="early-head"><div class="token-cell"><span class="token-avatar blue">'+t.symbol[0]+'</span><span><b>'+t.symbol+'</b><small>'+t.name+'</small></span></div><span class="signal '+t.signal.toLowerCase()+'">'+t.signal+'</span></div><div class="early-score"><strong>'+t.combined+'</strong><span>/100 RADAR</span></div><div class="early-metrics"><span><small>AGE</small><b>'+ageText(ago(t))+'</b></span><span><small>5M</small><b class="'+(t.m5>=0?'gain':'loss')+'">'+(t.m5>=0?'+':'')+t.m5.toFixed(1)+'%</b></span><span><small>BUYS</small><b>'+buys(t)+'%</b></span></div><a class="watch-button" href="'+t.url+'" target="_blank">OPEN LIVE PAIR ↗</a></article>').join('');
if($('#breakout-feed'))$('#breakout-feed').innerHTML=tokens.slice().sort((a,b)=>b.m5-a.m5).slice(0,6).map(t=>'<article class="breakout-card"><div><b>'+t.symbol+'</b><small>RADAR '+t.combined+' • '+buys(t)+'% buys</small></div><strong class="'+(t.m5>=0?'gain':'loss')+'">'+(t.m5>=0?'+':'')+t.m5.toFixed(2)+'%</strong><span>5M</span></article>').join('');
if($('#risk-feed'))$('#risk-feed').innerHTML=tokens.slice().sort((a,b)=>b.risk-a.risk).slice(0,6).map(t=>'<article class="risk-card"><div class="risk-card-top"><span><b>'+t.symbol+'</b><small>'+t.name+'</small></span><strong>'+t.risk+'<small>/100</small></strong></div><div class="risk-flags"><span>'+(t.risk>=70?'HIGH':t.risk>=45?'MEDIUM':'LOW')+'</span><em>'+compact(t.liquidity)+' liquidity</em></div></article>').join('');
if($('#activity-list'))$('#activity-list').innerHTML=tokens.slice(0,6).map(t=>'<div class="activity-item"><span class="token-avatar activity-avatar">'+t.symbol[0]+'</span><div class="activity-text"><b>'+t.symbol+'</b> '+(t.buys>=t.sells?'BUY':'SELL')+' pressure • <span class="'+(t.buys>=t.sells?'gain':'loss')+'">'+buys(t)+'% buys</span></div><span class="activity-time">LIVE</span></div>').join('');
let vol=tokens.reduce((s,t)=>s+t.volume,0);[['#stat-tracked',tokens.length],['#stat-new',tokens.filter(t=>ago(t)<24).length],['#stat-volume',compact(vol)],['#stat-hot',hot?.symbol||'—'],['#market-volume',compact(vol)]].forEach(([s,v])=>{if($(s))$(s).textContent=v});if($('#market-caption'))$('#market-caption').textContent=tokens.length+' live Solana candidates • direct market feed';if($('#feed-status'))$('#feed-status').textContent='● LIVE • '+tokens.length+' TOKENS';if($('#live-clock'))$('#live-clock').textContent='LIVE • '+new Date().toLocaleTimeString();
if($('#fomo-leaderboard'))$('#fomo-leaderboard').innerHTML=tokens.slice(0,10).map((t,i)=>'<a class="leader-item" href="'+t.url+'" target="_blank"><span class="leader-rank">#'+(i+1)+'</span><span class="leader-symbol">'+t.symbol+'</span><span class="leader-score">'+t.combined+'</span><span class="leader-move '+(t.m5>=0?'gain':'loss')+'">'+(t.m5>=0?'+':'')+t.m5.toFixed(1)+'%</span></a>').join('')}
async function load(){try{tokens=prepare(await getLive());render()}catch(e){console.error(e);if($('#feed-status'))$('#feed-status').textContent='● FEED ERROR';if($('#token-list'))$('#token-list').innerHTML='<tr><td colspan="9" class="empty">Live feed error. Refreshing connection…</td></tr>'}}
$$('.filter').forEach(b=>b.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter||'all';render()}));
$('#search')?.addEventListener('input',e=>{search=e.target.value.toLowerCase();render()});$('#search-button')?.addEventListener('click',()=>$('#search')?.focus());$('#refresh-button')?.addEventListener('click',load);
load();setInterval(load,15000);setInterval(()=>{if($('#live-clock'))$('#live-clock').textContent='LIVE • '+new Date().toLocaleTimeString()},1000);
})();
setInterval(()=>{if($('#live-clock'))$('#live-clock').textContent=new Date().toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',second:'2-digit'})},1000);