(()=>{const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let market=[],shown=[],filter='all',search='',timer;
const n=v=>Number.isFinite(Number(v))?Number(v):0, money=v=>{v=n(v);if(v>=1e9)return '$'+(v/1e9).toFixed(1)+'B';if(v>=1e6)return '$'+(v/1e6).toFixed(1)+'M';if(v>=1e3)return '$'+(v/1e3).toFixed(1)+'K';if(!v)return '—';return '$'+(v>=1?v.toLocaleString(undefined,{maximumFractionDigits:4}):v.toPrecision(4))},pct=v=>(n(v)>=0?'+':'')+n(v).toFixed(2)+'%',age=t=>t.pairCreatedAt?Math.max(0,(Date.now()-n(t.pairCreatedAt))/36e5):9999;
function risk(t){let r=25,l=n(t.liquidity),tx=n(t.buys1)+n(t.sells1);if(l<25000)r+=40;else if(l<100000)r+=20;if(age(t)<2)r+=12;if(tx<10)r+=10;return Math.min(100,r)}
function score(t){const tx=n(t.buys5)+n(t.sells5),bp=tx?n(t.buys5)/tx:.5;return Math.max(0,Math.min(100,Math.round(30+Math.min(25,Math.max(0,n(t.m5)*3))+Math.min(18,Math.max(0,n(t.h1)))+Math.min(15,(bp-.5)*35)+Math.min(12,Math.log10(Math.max(1,tx))*4)+(age(t)<24?10:0))))}
function prep(a){return a.filter(x=>x.address).map(x=>({...x,radar:score(x),risk:risk(x)})).sort((a,b)=>b.radar-a.radar)}
async function get(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
function img(t){return t.imageUrl||('https://dd.dexscreener.com/ds-data/tokens/solana/'+t.address+'.png')}
function coin(t){return '<div class="coin"><img src="'+img(t)+'" onerror="this.style.visibility=\'hidden\'"><span><b>'+t.symbol+'</b><small>'+t.name+'</small></span></div>'}
function card(t,label){return '<a class="card" href="'+t.url+'" target="_blank" rel="noopener"><div class="cardtop">'+coin(t)+'<span class="radar">'+label+' '+t.radar+'</span></div><div class="big">'+pct(t.m5)+'</div><div class="metrics"><span>AGE<b>'+ (age(t)<9999?Math.round(age(t))+'h':'—')+'</b></span><span>LIQUIDITY<b>'+money(t.liquidity)+'</b></span><span>BUYS<b>'+Math.round(n(t.buys)/(Math.max(1,n(t.buys)+n(t.sells)))*100)+'%</b></span></div><span class="linkbtn">OPEN LIVE PAIR ↗</span></a>'}
async function rugs(){try{const d=await get('/api/rug-pulls'),a=d.data||[];$('#rugCount').textContent=a.length;$('#rugGrid').innerHTML=a.length?a.map(x=>'<div class="rug-card"><div class="cardtop">'+coin(x)+'<span class="rug-pill">RUG ALERT</span></div><div class="rug-title">'+x.reasons[0]+'</div><div class="rug-meta">'+money(x.liquidity)+' LIQUIDITY • '+pct(x.h24)+' 24H</div><div class="reasons">'+x.reasons.map(r=>'<span>'+r+'</span>').join('')+'</div><a class="linkbtn" href="'+x.url+'" target="_blank" rel="noopener">OPEN LIVE PAIR ↗</a></div>').join(''):'<div class="empty">No current rug-pull signals detected in the scanned live candidates.</div>'}catch{$('#rugCount').textContent='—';$('#rugGrid').innerHTML='<div class="empty">Rug-watch feed unavailable — no fake alerts shown.</div>'}}
function render(){shown=market.filter(t=>!search||(t.symbol+' '+t.name+' '+t.address).toLowerCase().includes(search));if(filter==='hot')shown=shown.filter(t=>t.radar>=60);if(filter==='new')shown=shown.filter(t=>age(t)<24);if(filter==='gainers')shown=shown.filter(t=>t.h24>0);const hot=market[0];$('#tracked').textContent=market.length||'—';$('#newCount').textContent=market.filter(t=>age(t)<24).length||'0';$('#hot').textContent=hot?.symbol||'—';$('#volume').textContent=money(market.reduce((s,t)=>s+n(t.volume),0));$('#source').textContent=market.length?'Verified live market feed':'Waiting for verified feed';$('#marketInfo').textContent=market.length+' live Solana candidates • '+new Date().toLocaleTimeString();$('#status').textContent=market.length?'LIVE • '+market.length:'NO DATA';$('#clock').textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});
if(hot){$('#pickTitle').textContent=hot.symbol+' is the current radar leader';$('#pickText').textContent=hot.name;$('#pick').innerHTML='<a class="pick-card" href="'+hot.url+'" target="_blank" rel="noopener">'+coin(hot)+'<div class="score">'+hot.radar+'<small>/100</small></div></a><div class="bar"><i style="width:'+hot.radar+'%"></i></div><p>Verified live movement: '+pct(hot.m5)+' in 5m, '+money(hot.volume)+' 24h volume and '+money(hot.liquidity)+' liquidity.</p>'}else{$('#pick').innerHTML='<div class="empty">No verified data available. Nothing is being invented.</div>'}
const fresh=market.filter(t=>age(t)<=24).sort((a,b)=>n(a.pairCreatedAt)-n(b.pairCreatedAt)).slice(0,6);$('#newGrid').innerHTML=fresh.length?fresh.map(t=>card(t,'NEW')).join(''):'<div class="empty">No verified new-pool data available.</div>';$('#breakoutGrid').innerHTML=market.slice().sort((a,b)=>b.m5-a.m5).slice(0,6).map(t=>card(t,'RADAR')).join('')||'<div class="empty">No verified market data.</div>';
$('#riskGrid').innerHTML=market.slice().sort((a,b)=>b.risk-a.risk).slice(0,6).map(t=>'<a class="card" href="'+t.url+'" target="_blank" rel="noopener"><div class="cardtop">'+coin(t)+'<span class="radar">'+t.risk+'/100</span></div><div class="big">RISK '+t.risk+'</div><p>Calculated from live liquidity, age and transaction activity.</p><span class="linkbtn">OPEN LIVE PAIR ↗</span></a>').join('');
$('#table').innerHTML=shown.length?shown.map((t,i)=>'<tr><td>'+coin(t)+'</td><td>'+money(t.price)+'</td><td class="'+(t.h1>=0?'up':'down')+'">'+pct(t.h1)+'</td><td class="'+(t.h24>=0?'up':'down')+'">'+pct(t.h24)+'</td><td>'+money(t.volume)+'</td><td>'+money(t.liquidity)+'</td><td><span class="radar">'+t.radar+'</span></td><td><a class="arrow" href="'+t.url+'" target="_blank" rel="noopener">↗</a></td></tr>').join(''):'<tr><td colspan="8" class="empty">No matching verified tokens.</td></tr>'}
async function extras(){try{const pools=market.slice(0,8).map(t=>t.poolAddress).filter(Boolean).join(',');const [tr,news]=await Promise.all([pools?get('/api/trades?pools='+encodeURIComponent(pools)):{data:[]},get('/api/news')]);const td=tr.data||[],nd=news.data||[];$('#whalesGrid').innerHTML=td.length?td.slice(0,20).map(x=>{const t=market.find(z=>z.poolAddress===x.pool),time=x.timestamp?new Date(x.timestamp).toLocaleString():'Time unavailable';return '<div class="row"><div>'+coin(t||{symbol:'UNKNOWN',name:'Token not supplied',address:''})+'<span class="meta">'+time+' • '+(x.maker?'Wallet '+x.maker.slice(0,6)+'…'+x.maker.slice(-4):'Wallet not supplied')+'</span></div><strong>'+money(x.usd)+'</strong><a href="'+(t?.url||x.url)+'" target="_blank" rel="noopener">VIEW POOL ↗</a></div>'}).join(''):'<div class="empty">No verified large trades found in the current live pools.</div>';$('#newsGrid').innerHTML=nd.length?nd.slice(0,15).map(x=>'<div class="row"><div><strong>'+x.title+'</strong><span class="meta">'+x.source+' • '+(x.publishedAt?new Date(x.publishedAt).toLocaleString():'Time unavailable')+'</span></div><span></span><a href="'+x.link+'" target="_blank" rel="noopener">READ ↗</a></div>').join(''):'<div class="empty">No verified live headlines available right now.</div>'}catch(e){$('#whalesGrid').innerHTML='<div class="empty">Whale feed unavailable — no fake data shown.</div>';$('#newsGrid').innerHTML='<div class="empty">News feed unavailable — no fake data shown.</div>'}}
async function load(){try{const d=await get('/api/market');market=prep(d.data||[]);render();await Promise.all([extras(),rugs()]);$('#updated').textContent='Updated '+new Date(d.updatedAt||Date.now()).toLocaleTimeString()}catch(e){market=[];render();$('#status').textContent='FEED ERROR';$('#pick').innerHTML='<div class="empty">Live market feed unavailable. No fake data is displayed.</div>';$('#table').innerHTML='<tr><td colspan="8" class="empty">Live market feed unavailable. Refresh to retry.</td></tr>'}}
$$('.filters button').forEach(b=>b.onclick=()=>{$$('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;render()});$('#search').oninput=e=>{search=e.target.value.trim().toLowerCase();clearTimeout(timer);timer=setTimeout(render,100)};$('#searchBtn').onclick=()=>{$('#search').focus();render()};$('#refresh').onclick=load;load();setInterval(load,60000);setInterval(()=>{$('#clock').textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})},1000)})();