const H={Accept:'application/json'};const N=v=>Number.isFinite(Number(v))?Number(v):0;
async function get(u,ms=9000){const c=new AbortController(),tm=setTimeout(()=>c.abort(),ms);try{const r=await fetch(u,{headers:H,signal:c.signal});const text=await r.text();let body;try{body=JSON.parse(text)}catch{}return{ok:r.ok,status:r.status,body}}finally{clearTimeout(tm)}}
function dex(x){const q=x.txns||{},c=x.priceChange||{},v=x.volume||{},b=x.baseToken||{};return{address:String(b.address||''),poolAddress:String(x.pairAddress||''),symbol:String(b.symbol||'UNKNOWN').toUpperCase(),name:String(b.name||b.symbol||'Unknown token'),price:N(x.priceUsd),m5:N(c.m5),m15:N(c.m15),h1:N(c.h1),h24:N(c.h24),volume:N(v.h24),volume5:N(v.m5),volume1:N(v.h1),liquidity:N(x.liquidity?.usd),buys:N(q.h24?.buys),sells:N(q.h24?.sells),buys5:N(q.m5?.buys),sells5:N(q.m5?.sells),buys1:N(q.h1?.buys),sells1:N(q.h1?.sells),pairCreatedAt:N(x.pairCreatedAt),url:String(x.url||('https://dexscreener.com/solana/'+x.pairAddress))}}
function add(out,pairs){for(const x of pairs||[]){if(x?.chainId==='solana'&&x.baseToken?.address)out.push(dex(x))}}
export default async function handler(req,res){res.setHeader('Cache-Control','s-maxage=12, stale-while-revalidate=30');let out=[],source='DEXSCREENER LIVE';
for(const q of ['SOL','meme','pump','dog','cat','inu','ai','moon']){try{const r=await get('https://api.dexscreener.com/latest/dex/search?q='+encodeURIComponent(q));if(r.ok)add(out,r.body?.pairs)}catch{}}
if(out.length<10){try{const r=await get('https://api.geckoterminal.com/api/v2/networks/solana/trending_pools?page=1');if(r.ok&&Array.isArray(r.body?.data)){source='GECKOTERMINAL LIVE';for(const x of r.body.data){const a=x.attributes||{},id=String(x.id||'').replace(/^solana_/,'').split('_')[0],rel=String(x.relationships?.base_token?.data?.id||'').replace(/^solana_/,'');const pc=a.price_change_percentage||{},v=a.volume_usd||{},t=a.transactions||{};out.push({address:rel||id,poolAddress:id,symbol:String(a.name||'UNKNOWN / SOL').split(' / ')[0],name:String(a.name||'UNKNOWN / SOL').split(' / ')[0],price:N(a.base_token_price_usd),m5:N(pc.m5),m15:N(pc.m15),h1:N(pc.h1),h24:N(pc.h24),volume:N(v.h24),volume5:N(v.m5),volume1:N(v.h1),liquidity:N(a.reserve_in_usd),buys:N(t.h24?.buys),sells:N(t.h24?.sells),buys5:N(t.m5?.buys),sells5:N(t.m5?.sells),buys1:N(t.h1?.buys),sells1:N(t.h1?.sells),pairCreatedAt:a.pool_created_at?Date.parse(a.pool_created_at):0,url:'https://geckoterminal.com/solana/pools/'+id})}}catch{}}
const seen=new Set();out=out.filter(x=>x.address&&!seen.has(x.address)&&seen.add(x.address)).sort((a,b)=>(b.volume+b.liquidity*.15)-(a.volume+a.liquidity*.15)).slice(0,80);
if(!out.length)return res.status(503).json({error:'Live Solana feed unavailable',source:'NO_UPSTREAM'});
res.status(200).json({data:out,source,updatedAt:new Date().toISOString()})}